### ISSUE TITLE
[Questions]com.android.ddmlib.InstallException: Failed to install all 

### ISSUE THREAD

**Issue by lawrencehui** [januslo/react-native-sunmi-inner-printer#1]
I encounter this error while trying to do the run-android command. I have enable to the developer mode and USB debugging on my Sunmi v1. Have you encounter this while running react-native on Sunmi devices before?

error that I see
* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to install all 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Thanks in advance

**Comment by januslo** [comment]
Allways， try to install manually with adb command after build.

发自我的 iPhone

**Comment by lawrencehui** [comment]
@januslo, thanks, I think my issue is I can't authorise USB debugging, I applied for the 開發調試員 but couldn't get the verification code, have you encountered similar issue and how did you solve it?

**Comment by januslo** [comment]
Are you applied via phone number? Or email? I have never try email.

发自我的 iPhone

**Comment by lawrencehui** [comment]
I tried both but the phone keep saying error please try again later. Do I need to upload the apk to the partner portal first? 

Right now when I do "adb devices" it is still saying unauthorised

**Comment by januslo** [comment]
You need to register and login in the phone. Try to register via debugging setting. 

发自我的 iPhone

**Comment by lawrencehui** [comment]
Yes I did and I got to the page that I can input a Chinese phone number or email page and when I try to click "获取验证码" it then said "error, please try again later" (in Chinese). I think maybe something wrong with their server side? Do you know anyone from Sunmi I can contact with about the issue?

**Comment by januslo** [comment]
Are you sure is not the internet connection issue?

发自我的 iPhone

**Comment by januslo** [comment]
Hi. I check you profile that shows you are in HK. If you can read Chinese, you can ask for help in the official QA board.

发自我的 iPhone

**Comment by januslo** [comment]
if your phone is brought from the partner ship merchant, you may need to contact that partner. I brought those machines before, but I found not easy to contact that third party so I re-buy a need one from official site. 
See the question referring: http://feedback.sunmi.com/?/question/806

**Comment by lawrencehui** [comment]
cool thanks @januslo I will try to contact them 👍
