### ISSUE TITLE
react native link error

### ISSUE THREAD

**Issue by hllhui** [januslo/react-native-sunmi-inner-printer#10]
i try "react-native link react-natvie-sunmi-inner-printer"
have an error:

{ Error: Cannot find module .../node_modules/react-natvie-sunmi-inner-printer/package.json'

how to solve it ?

**Comment by januslo** [comment]
react-**natvie**-sunmi-inner-printer 
???

**Comment by januslo** [comment]
my bad..  the typo issue of link command in the readme file has just fixed. @hllhui

**Comment by hllhui** [comment]
react-native-sunmi-inner-scanner 那里你也写错，我也没留意，直接copy
