### ISSUE TITLE
打印机接口问题相关

### ISSUE THREAD

**Issue by liseen315** [januslo/react-native-sunmi-inner-printer#11]
您好，首先感谢提供java封装
现在使用遇到如下问题:
1.怎么切纸？我看官方文档提供了cutPaper 接口，但是没看到有对应封装，我查看了iwoyouservice的接口也没发现有暴露，不知道如何打印完一张小票后怎么切
2.printBarCode，printQRCode两个接口首个参数都是string 类型的data,不知道能否提供一个示例的参数格式.不知道传什么样的进去能用..

谢谢！

**Comment by januslo** [comment]
@liseen315 
1 。 首先 V1 没有切纸，如果需要用到其他型号，直接 使用 sendRAWData 发送 切纸指令，因为我不清楚切纸的具体指令，一下用 打开钱柜的 例子
```javascript
var base64 = require('base64-js');

async openDrawer(){
    var openDrawerCommand = [0x10,0x14,0x00,0x00,0x00];
    var openDrawerCommandStr = base64.fromByteArray(openDrawerCommand);
    try{
     await SunmiInnerPrinter.sendRAWData(openDrawerCommandStr);
      await SunmiInnerPrinter. printOriginalText("\n"); // should no need, just for test to ensure the first command was flushed.
    }catch(e){
      alert('issue',+e.message);
     console.log(e)
    }
}

```

2. .printBarCode，printQRCode两个接口的第一个参数就是barcode 或者QRCode 的具体内容，事前不需要手动生成图片或者什么其他各试，比如生成barcode『1234567890』，你直接输入『1234567890』就ok了，又比如要生成『hello』的qrcode，你直接输入『hello』就行。

**Comment by januslo** [comment]
#6 中有讨论过这个问题

**Comment by liseen315** [comment]
@januslo 谢谢回复！

**Comment by januslo** [comment]
解决了么？


发自我的 iPhone

**Comment by januslo** [comment]
Close for no response .
