### ISSUE TITLE
是否需要调试授权

### ISSUE THREAD

**Issue by hllhui** [januslo/react-native-sunmi-inner-printer#12]
我程序写不进去
Installing APK 'app-debug.apk' on 'V1 - 5.1' for app:debug
08:59:27 E/1439963706: Error while uploading app-debug.apk : Unknown failure ([CDS]close[0])

是什么原因

**Comment by januslo** [comment]
尝试一下 用
```bash
 adb install -r android/app/build/outputs/apk/app-debug.apk
````
直接安装。
如果不行，就查看开发者选项的授权，确定授权之后重启一下。
我经常要手动安装并且重启的。
这个设备对开发不怎么友好。
