### ISSUE TITLE
How to use this project with Expo

### ISSUE THREAD

**Issue by nsisodiya** [januslo/react-native-sunmi-inner-printer#16]
Expo documentation says I cannot use this project because it needs `react-native link`.
https://github.com/react-community/create-react-native-app/blob/35ab2866b1c738e8bd64cb33232510a1341cf2ab/README.md#what-are-the-limitations-of-create-react-native-app

it is possible to modify this project so that `react-native link` step is not needed at all.

Thanks.

**Comment by januslo** [comment]
Plz see the read me

发自我的 iPhone

**Comment by januslo** [comment]
close while no any further discussions.
