### ISSUE TITLE
Regrading Android version

### ISSUE THREAD

**Issue by nsisodiya** [januslo/react-native-sunmi-inner-printer#17]
I got SunMI V1 POS, it has Android 5.1 on it.
Instructions on https://facebook.github.io/react-native/docs/getting-started.html show 6.0
![image](https://user-images.githubusercontent.com/333455/31298075-1608015a-ab06-11e7-974c-2673781b28e4.png)

In order to run this project, I need to install it. please suggest me what to do?

**Comment by januslo** [comment]
Rest native using gradle to build, it ok to run at 5.x

发自我的 iPhone

**Comment by januslo** [comment]
close while no any further  discussions.
