### ISSUE TITLE
请问怎么封装成MUI使用？

### ISSUE THREAD

**Issue by qq727127158** [januslo/react-native-sunmi-inner-printer#19]
本人不懂react-native，但是目前手上有一个项目是使用MUI做的移动端APP,目前有个需求，需要在APP中使用商米来打印条码和图片。由于打印条码和图片的特殊性导致不能直接单纯的传指令码，可能需要结合参数来进行打印。但是目前的项目是MUI开发，不知道怎么调用原生的商米开发工具。希望可以指导一下！

**Comment by januslo** [comment]
看我首页提供的官方例子连接.

发自我的 iPhone

**Comment by januslo** [comment]
https://github.com/shangmisunmi/SunmiPrinterDemo


发自我的 iPhone

**Comment by januslo** [comment]
再者，只有MUI无底层服务支持应该不行。直接在设备上开发吧。

发自我的 iPhone
