### ISSUE TITLE
how to cut the paper?

### ISSUE THREAD

**Issue by mcrucesi** [januslo/react-native-sunmi-inner-printer#24]
Hello, I'm in need of paper cutting in the T1

(Sorry in advance for my English and my explanations).

Can you help me perform the functionality to cut the paper for the printer t1. I can perform the resect tests

I remain attentive to your comments

Thanks.

Marcelo Cruces.

**Comment by januslo** [comment]
Plz try to find the closed issues, I remember there is a simple about paper cut function of T1

发自我的 iPhone

**Comment by januslo** [comment]
@marcelocruces  hi, plz try to find some discussion before in #6 .

**Comment by januslo** [comment]
you can refer this as long as you can read chinese #11.  Any more help request plz let me know,
