### ISSUE TITLE
undefined is not an object 

### ISSUE THREAD

**Issue by lucaspojo** [januslo/react-native-sunmi-inner-printer#25]
Hi, 
The sample demo dont work :(

undefined is not an object (evaluating '_reactNativeSunmiInnerPrinter2.default.setAlignment')

How to fix ?

**Comment by januslo** [comment]
The demo install the plugin with path../, make sure to clone hold project with full structure before you run and test it.

发自我的 iPhone

**Comment by lucaspojo** [comment]
@januslo This is my package.json 

{
  "name": "examples",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-sunmi-inner-printer": "/Users/lucaspojo/Documents/GitHub/react-native-sunmi-inner-printer-0.1.5/android/src/main/java/com/sunmi"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by januslo** [comment]
U may need to config the dependency path to the folder where the package.json in.

发自我的 iPhone

**Comment by januslo** [comment]
The dependency of demo may massed. you may try to remove the plugin with npm command then reinstall  with the git location directly. as 

**Step 1.**

install with npm: [Check in NPM](https://www.npmjs.com/package/react-native-sunmi-inner-printer)

```bash
npm install react-native-sunmi-inner-printer --save
```

or you may need to install via the clone address directly:

```bash 
npm install https://github.com/januslo/react-native-sunmi-inner-printer.git --save
```

**Step 2:**

Links this plugin to your project.

```bash
react-native link react-native-sunmi-inner-printer
``` 

I use this plugin in my own projects and it works will, so I am what you are facing should be installation issue only.

**Comment by lucaspojo** [comment]
I can't get this printer to work. I shouldn't have Buyed that device. Thanks anyway.

**Comment by januslo** [comment]
Don’t give up. Maybe my plugins problem, you can try the official demo to test your device. See the link I provided in read me file.

发自我的 iPhone

**Comment by bhoomika911** [comment]
I have same issue as per attachment. Can you please help? It is urgent.

![error](https://user-images.githubusercontent.com/26411261/40932700-da753f86-684c-11e8-8bb7-0190e8ffbff7.jpeg)

**Comment by januslo** [comment]
Seems your native lib not load, what devices you are working with?

发自我的 iPhone

**Comment by MarioRozic** [comment]
C:\---\Desktop\projects\vb-rn-test\AwesomeProjectNative\node_modules\react-native-sunmi-inner-printer\android\src\main\java\com\sunmi\innerprinter\SunmiInnerPrinterPackage.java:15: error: method does not override or implement a method from a supertype
  @Override
  ^
1 error
:react-native-sunmi-inner-printer:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-sunmi-inner-printer:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 16.722 secs
Could not build the app, read the error above for details.

Do you have any idea what does this mean ??

**Comment by januslo** [comment]
its about the RN version, plz see the last pull request #26

**Comment by MarioRozic** [comment]
I did it thanks!

**Comment by januslo** [comment]
close as resolved
