### ISSUE TITLE
Disable printer cutting words in the line

### ISSUE THREAD

**Issue by linkas45** [januslo/react-native-sunmi-inner-printer#29]
Hi there, I would like to know, whether it's possible to disable default printing till the end of the line rather making it print full words by not cutting them. Now if a printer has to print a sentence "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed" the part "t, sed" goes into another line rather than having full words in another line: "elit, sed". Is it possible to solve this issue with Sunmi device? Thanks

**Comment by januslo** [comment]
May not disable the line wrapping. You can calculates the word count with get printed length and font size. More information, you may need to check the official documents.

发自我的 iPhone

**Comment by thuanphat2009** [comment]
> Hi there, I would like to know, whether it's possible to disable default printing till the end of the line rather making it print full words by not cutting them. Now if a printer has to print a sentence "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed" the part "t, sed" goes into another line rather than having full words in another line: "elit, sed". Is it possible to solve this issue with Sunmi device? Thanks

Hello, how do you fix it, please teach me thank you
