### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by RobertStuff** [januslo/react-native-sunmi-inner-printer#3]
Hi good day.. I would like to ask about the installation. Im having problem installing with npm.. Thanks

**Comment by RobertStuff** [comment]
npm install januslo/react-natvie-sunmi-inner-printer --save
npm ERR! git clone --template=/Users/STUFF/.npm/_git-remotes/_templates --mirror git@github.com:januslo/react-natvie-sunmi-inner-printer.git /Users/STUFF/.npm/_git-remotes/git-github-com-januslo-react-natvie-sunmi-inner-printer-git-4292fbd7: Cloning into bare repository '/Users/STUFF/.npm/_git-remotes/git-github-com-januslo-react-natvie-sunmi-inner-printer-git-4292fbd7'...
npm ERR! git clone --template=/Users/STUFF/.npm/_git-remotes/_templates --mirror git@github.com:januslo/react-natvie-sunmi-inner-printer.git /Users/STUFF/.npm/_git-remotes/git-github-com-januslo-react-natvie-sunmi-inner-printer-git-4292fbd7: Permission denied (publickey).
npm ERR! git clone --template=/Users/STUFF/.npm/_git-remotes/_templates --mirror git@github.com:januslo/react-natvie-sunmi-inner-printer.git /Users/STUFF/.npm/_git-remotes/git-github-com-januslo-react-natvie-sunmi-inner-printer-git-4292fbd7: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/STUFF/.npm/_git-remotes/_templates --mirror git@github.com:januslo/react-natvie-sunmi-inner-printer.git /Users/STUFF/.npm/_git-remotes/git-github-com-januslo-react-natvie-sunmi-inner-printer-git-4292fbd7: 
npm ERR! git clone --template=/Users/STUFF/.npm/_git-remotes/_templates --mirror git@github.com:januslo/react-natvie-sunmi-inner-printer.git /Users/STUFF/.npm/_git-remotes/git-github-com-januslo-react-natvie-sunmi-inner-printer-git-4292fbd7: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/STUFF/.npm/_git-remotes/_templates --mirror git@github.com:januslo/react-natvie-sunmi-inner-printer.git /Users/STUFF/.npm/_git-remotes/git-github-com-januslo-react-natvie-sunmi-inner-printer-git-4292fbd7: and the repository exists.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/STUFF/.nvm/versions/node/v4.2.2/bin/node" "/Users/STUFF/.nvm/versions/node/v4.2.2/bin/npm" "install" "januslo/react-natvie-sunmi-inner-printer" "--save"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/STUFF/.npm/_git-remotes/_templates --mirror git@github.com:januslo/react-natvie-sunmi-inner-printer.git /Users/STUFF/.npm/_git-remotes/git-github-com-januslo-react-natvie-sunmi-inner-printer-git-4292fbd7
npm ERR! Cloning into bare repository '/Users/STUFF/.npm/_git-remotes/git-github-com-januslo-react-natvie-sunmi-inner-printer-git-4292fbd7'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by januslo** [comment]
Plz try to install with the the clone URL . Master is the same with the last release currently .

发自我的 iPhone

**Comment by RobertStuff** [comment]
Hi I have already try to install clone and include the settings but Im having this error

MainApplication.java:36: error: cannot find symbol
            new SunmiInnerPrinterPackage()
                ^
  symbol: class SunmiInnerPrinterPackage
1 error
:app:compileDebugJavaWithJavac FAILED

**Comment by RobertStuff** [comment]
My fault forgot the import.. Thanks for you immediate response.. Cheers..
