### ISSUE TITLE
Print with JS in HTML

### ISSUE THREAD

**Issue by hewrin** [januslo/react-native-sunmi-inner-printer#33]
Hi,

Thanks for publishing this library,

In the SunmiPrinter documentation, they say that there are 3 ways to print. One of the ways is via webview and to use html & JS, Is it possible with your library?

Thanks in advance

**Comment by januslo** [comment]
This plugin is limited use by the SUMI devices, not the normal one. Further more, this is a react native plugin, can run with RN even only. 

In a word, this plugin can run at SUMI devices with RN App only.

发自我的 iPhone

**Comment by hewrin** [comment]
Thanks for the reply.

Is the plugin compatible with this device?

https://sunmi.com/en/v2Pro.html

**Comment by januslo** [comment]
Not test yet, but should can be use in pro. 

发自我的 iPhone

**Comment by januslo** [comment]
Emmm , we are not the official plugin that you may better query the official before using this plugin in the untested device.

发自我的 iPhone

**Comment by hewrin** [comment]
Thank you very much for your answers, I'll close this now

**Comment by mustafaxoodiye** [comment]
Hi,

as far as my knowledge goes, this library works with RN, but in my project, I am using Expo. 
Is there any other library that is made for Expo, if you know? Also, is there a way that I can use this library in my Expo project with SUNMI inner printer?

Thanks in advance
