### ISSUE TITLE
help with p1

### ISSUE THREAD

**Issue by muriloSanto** [januslo/react-native-sunmi-inner-printer#42]
Hello.

Can you give some help with my p1? I'm trying to use it and develop a software using your lib, but I can't even bind my equipment to my partner account. Can you help me with that? Please.

**Comment by januslo** [comment]
About partner account issue you may need to contact the official support.

发自我的 iPhone

**Comment by muriloSanto** [comment]
I can't get any responses from them. Is it possible to give me some help with that, please?

**Comment by januslo** [comment]
you may need to check the support web site: https://sunmi.com/support/ or call 400-6666-509 during  9:00-21:00 GMT+8 . I am sorry I can do nothing about the account issue.
