### ISSUE TITLE
How examples/index.android.js work in real life

### ISSUE THREAD

**Issue by buiquangduc** [januslo/react-native-sunmi-inner-printer#48]
Hi Januslo,

This is not an issue by the way, but I've read the README.md file and all the issues opened on this repository and did not find an answer.

Currently, I've integrated `examples/index.android.js` file into my project, but I do not own a Sunmi V1 device to test this file. So I wonder how can the file `examples/index.android.js` work in real life.

In my imagination, I will need to connect the Sunmi V1 device to my phone (via Bluetooth?), then I can using all the functions listed on the `examples/index.android.js` file?

Sorry for submitting that kind of question :(

**Comment by januslo** [comment]
You need Sunmi devices. This plugin run in sunmi devices only.

发自我的 iPhone

**Comment by buiquangduc** [comment]
Thanks, I've tested with real device and it is working as expected!
