### ISSUE TITLE
[Remark-Need to Check]Error not show to font-end JS when error occurs in printBitmap

### ISSUE THREAD

**Issue by januslo** [januslo/react-native-sunmi-inner-printer#6]
// TODO:
Refer #5 , no any error shows when fails to parse the base64 string.

**Comment by kibot914** [comment]
Hi januslo,

We are POS developer in Hong Kong ( www.kios.tech ) and looking for some library which can make use of our application on top of Sunmi's hardware.

Your library is interesting and maybe useful to use, can you please give me some example and demo of using your script in the JS file. 

Many thanks. You may also contact us by admin@kios.tech

**Comment by januslo** [comment]
Details or only basic example? Or you may provide your scenario in detail that I can do some samples.

发自我的 iPhone

**Comment by kibot914** [comment]
Thanks for reply man.
I think basic example is fine , cause I don't want to bother you too much.

For you reference ,please check out the attached pictures, our current system will print out some receipts for customers. 

![036oeo063fb64ef62af124px](https://user-images.githubusercontent.com/13725006/27209191-f64d0b9e-527c-11e7-8e2e-419204bde86c.jpg)

**Comment by januslo** [comment]
Let me try later


发自我的 iPhone

**Comment by januslo** [comment]
@kibot914 
See examples folder of the source code that you can find a simple example of printing receipt.

**Comment by kibot914** [comment]
Thanks buddy.

So you are a developer ? or Free licenser ? Or you are in house developer of sunmi ?

**Comment by januslo** [comment]
I am a technical guy of a internet company. Create and share this plugin during the my development with Sunmi V1 which choose by the investigation of our technical team. As I mentioned in the readme file, this is not the official plugin with the official support.

**Comment by kibot914** [comment]
I see, awesome bro.
I am going to purchase a V1 Model to test it out.
How do you think about Sunmi 's devices ? It is reliable ?

**Comment by januslo** [comment]
The quality is good, but the security setting is terrible for development. Printing is good be hard to say perfect. Inner Scanner is fast enough (so much faster then zxing lib).
Easy to use but not so nice to developer.

**Comment by januslo** [comment]
I got no T1 devices

发自我的 iPhone

**Comment by kibot914** [comment]
I see, never mind.

But do you think I can send and declare an array of byte in Javascript ( like the attached photo ) and send the raw data to trigger the cash drawer ?

<img width="1069" alt="screen shot 2017-06-23 at 4 16 13 pm" src="https://user-images.githubusercontent.com/13725006/27472890-bce301fc-582f-11e7-9f11-7189a40adfdd.png">

**Comment by januslo** [comment]
You may try as 

```javascript
var base64 = require('base64-js');

async openDrawer(){
    var openDrawerCommand = [0x10,0x14,0x00,0x00,0x00];
    var openDrawerCommandStr = base64.fromByteArray(openDrawerCommand);
    try{
     await SunmiInnerPrinter.sendRAWData(openDrawerCommandStr);
      await SunmiInnerPrinter. printOriginalText("\n"); // should no need, just for test to ensure the first command was flushed.
    }catch(e){
      alert('issue',+e.message);
     console.log(e)
    }
}

```

base64js should be included in the react-native or you may need to install via https://github.com/beatgammit/base64-js

**Comment by januslo** [comment]
@kibot914  check above... em... but I have not tested.

**Comment by kibot914** [comment]
It's ok , thanks bro, I will test it out later and tell you the result

**Comment by januslo** [comment]
@kibot914 who's the thing.

**Comment by kibot914** [comment]
Still don't have time to try it out yet, pretty busy with our customers right now

**Comment by kibot914** [comment]
Hey @januslo  bro, 

Thanks for you help last time and finally I get some time to start integration with Sunmi.
I think your library works pretty well actually.

However, I would like to know is the following function in SunmiInnerPrinterModule.java not avaliable right now ?
`
// public void getPrinterModal(Promise p){
// }
`
Coz we would like to differentiate the model of the sunmi devices that users are using.
Anyway, thanks a lot.

**Comment by januslo** [comment]
@kibot914  I can try to implement it but I got no devices to test with in these days. Can you help to test?

**Comment by kibot914** [comment]
@januslo  Sure no problem, wait for your good news

**Comment by kibot914** [comment]
Hey bro,

I am sorry to tell you that I think the function doesn't work after a several try, here's the debug message
![screenshot_2017-08-12-15-54-51](https://user-images.githubusercontent.com/13725006/29239073-0d87b7d8-7f77-11e7-9635-0f9db7c86749.png)

**Comment by januslo** [comment]
if got log cat messages would be better

发自我的 iPhone

**Comment by kibot914** [comment]
<img width="1336" alt="screen shot 2017-08-13 at 2 13 47 pm" src="https://user-images.githubusercontent.com/13725006/29246651-15f74010-8034-11e7-8a0f-c6edfd2c7609.png">
<img width="2526" alt="screen shot 2017-08-13 at 2 16 25 pm" src="https://user-images.githubusercontent.com/13725006/29246652-16236ae6-8034-11e7-920b-55d91fd42a81.png">
<img width="2546" alt="screen shot 2017-08-13 at 2 21 08 pm" src="https://user-images.githubusercontent.com/13725006/29246653-163f1aca-8034-11e7-9ee2-a999cdd1e13b.png">


Hey bro, which part of log data do you want to grep specifically ?

**Comment by januslo** [comment]
I don't think it is the native code issue.  plz make sure the old one is completed replaced with the v 0.1.4 one. @kibot914
