### ISSUE TITLE
PrinterStatus Event not calling any actions (example uses deprecated DeviceEventEmitter)

### ISSUE THREAD

**Issue by NqCompiler** [januslo/react-native-sunmi-inner-printer#62]
Hi,

Thanks for this project!
The Event "PrinterStatus" does not trigger any actions.
You are using DeviceEventEmitter in your example (index.android.js).
This seems to be deprecated and should be replaced with NativeEventEmitter.

I am using react-native 0.63.4
1. Is it still possible to use DeviceEventEmitter and I am doing something wrong? (I am using the exact code of your example but with another react-native version)
2. Can you provide an example with the new NativeEventEmitter? (I have tried and did not succeed)

**Comment by kev-ac** [comment]
@NqCompiler Did you find a solution for this problem? I am facing the exact same issue with a new project on the latest RN version. 

Edit: Calling printerInit() function on startup seems to do the trick.
See example in my forked repo: [/example/App.js](https://github.com/kev-ac/react-native-sunmi-v2-printer/blob/76d27c8b437ebf29c5e887e12208782a17c779b2/example/App.js)

**Comment by NqCompiler** [comment]
I didn't find a solution and thanks for your edit. I will try it out and close the issue asap.
