### ISSUE TITLE
Help needed for Expo based project

### ISSUE THREAD

**Issue by nsisodiya** [januslo/react-native-sunmi-inner-printer#9]
I am developing a project using Expo. How I can use this project with https://expo.io/
I have recently purchased SunMi Android POS. I do not know how to use this project. I need for printing from my mobile app.

**Comment by januslo** [comment]
SunMi plugins need to work with the devices only, cannot runs any online demos for native libs are required for this plugin.

**Comment by januslo** [comment]
if u run and test with the devices instead of emulator, you may just install this plugin following the steps of Installation of the read me.

**Comment by SistemaMetha** [comment]
@nsisodiya 
I also have the same product, did you get any results?

I'm using react native - expo.
